# Generated by Django 6.0.1 on 2026-02-20 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ticket_type',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
    ]
