# Generated by Django 6.0.1 on 2026-02-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_booking_ticket_type_remove_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total_person',
            field=models.IntegerField(default=1),
        ),
    ]
