# Generated by Django 6.0.1 on 2026-05-12 12:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.uuid4),
        ),
    ]
